name: Jazzy

on:
  push:
    branches: [main]
    paths:
      - '.github/workflows/jazzy.yml'
      - '.jazzy.yaml'
      - '**/*.md'
      - '**/*.jpg'
      - 'Gemfile*'
      - 'Package*'
      - 'Sources/**/*.swift'
  pull_request:
    paths:
      - '.github/workflows/jazzy.yml'
      - '.jazzy.yaml'
      - '**/*.md'
      - '**/*.jpg'
      - 'Gemfile*'
      - 'Package*'
      - 'Sources/**/*.swift'

concurrency:
  group: jazzy-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  Jazzy:
    permissions:
      contents: write  # for Git to git push
    runs-on: macos-14
    env:
      DEVELOPER_DIR: /Applications/Xcode_15.4.app
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
        with:
          egress-policy: audit

      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
      - name: Install SourceKitten
        run: brew install sourcekitten
      - run: swift build
      - name: Generate documentation json
        run: sourcekitten doc --spm --module-name Yams > yams.json
      - uses: ruby/setup-ruby@0481980f17b760ef6bca5e8c55809102a0af1e5a # v1.263.0
        with:
          ruby-version: 3.3.3
          bundler-cache: true
      - name: Run jazzy
        run: bundle exec jazzy --clean --sourcekitten-sourcefile yams.json
      - name: Validate documentation coverage
        run: |
          if ruby -rjson -e "j = JSON.parse(File.read('docs/undocumented.json')); exit j['warnings'].length != 0"; then
            echo "Undocumented declarations:"
            cat docs/undocumented.json
            exit 1
          fi
      - name: Upload Artifact
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: API Docs
          path: docs
      - name: Push to gh-pages
        if: github.event_name == 'push'
        run: |
          git config --global user.email "${GITHUB_ACTOR}"
          git config --global user.name "${GITHUB_ACTOR}@users.noreply.github.com"
          git clone "https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git" out

          cd out
          git checkout gh-pages
          git rm -rf .
          cd ..

          cp -a docs/. out/.
          cd out

          git add -A
          git commit -m "Automated deployment to GitHub Pages: ${GITHUB_SHA}" --allow-empty

          git push origin gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
