name: Nightly

on:
  push:
    branches: [main]
    paths:
      - '.github/workflows/nightly.yml'
      - 'Package*'
      - 'Sources/**/*.[ch]'
      - 'Sources/**/*.swift'
      - 'Sources/**/module.modulemap'
      - 'Tests/**/*.swift'
      - 'Tests/**/*.ya?ml'
  pull_request:
    paths:
      - '.github/workflows/nightly.yml'
      - 'Package*'
      - 'Sources/**/*.[ch]'
      - 'Sources/**/*.swift'
      - 'Sources/**/module.modulemap'
      - 'Tests/**/*.swift'
      - 'Tests/**/*.ya?ml'
  schedule:
    - cron: '0 4 * * *'

concurrency:
  group: nightly-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  Nightly:
    runs-on: ubuntu-latest
    container:
      image: swiftlang/swift:nightly
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
        with:
          egress-policy: audit

      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
      - run: swift --version
      - run: YAMS_DEFAULT_ENCODING=UTF16 swift test --parallel
      - run: YAMS_DEFAULT_ENCODING=UTF8 swift test --parallel
