name: pod lib lint

on:
  push:
    branches: [main]
    paths:
      - '.github/workflows/pod_lib_lint.yml'
      - '*.podspec'
      - 'Gemfile*'
      - 'Sources/**/*.[ch]'
      - 'Sources/**/*.swift'
  pull_request:
    paths:
      - '.github/workflows/pod_lib_lint.yml'
      - '*.podspec'
      - 'Gemfile*'
      - 'Sources/**/*.[ch]'
      - 'Sources/**/*.swift'

concurrency:
  group: pod-lib-lint-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  pod_lib_lint:
    name: pod lib lint
    runs-on: macos-14
    env:
      DEVELOPER_DIR: /Applications/Xcode_15.4.app
    strategy:
      matrix:
        platform: [macOS, iOS, tvOS, visionOS]
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
        with:
          egress-policy: audit

      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
      - run: bundle install --path vendor/bundle
      - if: matrix.platform == 'visionOS'
        run: xcodebuild -downloadPlatform visionOS
      - run: bundle exec pod lib lint --platforms=${{ matrix.platform }} --verbose
